spring:
  profiles:
    include: secret
  datasource:
    url: jdbc:h2:mem:buskers
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      path: /h2-console
      enabled: true
  security:
    user:
      password: 1
